In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5941, 7165, 600, 8687],
 [5941, 7165, 600, 9590],
 [5941, 1169, 600, 5564],
 [7195, 3913, 381, 7278, 7385],
 [7195, 3913, 381, 7278, 1307],
 [3679, 5941, 8, 600, 9619],
 [3116, 4513, 5282, 7278]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5941 7165  600 8687]
 [   0    0    0    0 5941 7165  600 9590]
 [   0    0    0    0 5941 1169  600 5564]
 [   0    0    0 7195 3913  381 7278 7385]
 [   0    0    0 7195 3913  381 7278 1307]
 [   0    0    0 3679 5941    8  600 9619]
 [   0    0    0    0 3116 4513 5282 7278]]


In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 108ms/step


array([[[ 2.55517252e-02,  3.14174183e-02, -3.67821939e-02,
          1.47368759e-03, -2.91334037e-02,  1.23359784e-02,
         -4.56507914e-02, -4.92634550e-02,  3.45454700e-02,
          1.13060698e-02],
        [ 2.55517252e-02,  3.14174183e-02, -3.67821939e-02,
          1.47368759e-03, -2.91334037e-02,  1.23359784e-02,
         -4.56507914e-02, -4.92634550e-02,  3.45454700e-02,
          1.13060698e-02],
        [ 2.55517252e-02,  3.14174183e-02, -3.67821939e-02,
          1.47368759e-03, -2.91334037e-02,  1.23359784e-02,
         -4.56507914e-02, -4.92634550e-02,  3.45454700e-02,
          1.13060698e-02],
        [ 2.55517252e-02,  3.14174183e-02, -3.67821939e-02,
          1.47368759e-03, -2.91334037e-02,  1.23359784e-02,
         -4.56507914e-02, -4.92634550e-02,  3.45454700e-02,
          1.13060698e-02],
        [ 2.48964876e-03, -4.97074500e-02,  1.51848309e-02,
          2.07346790e-02, -4.94556502e-03,  4.33007367e-02,
         -1.95984971e-02,  2.02580579e-02,  9.135760

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 5941, 7165,  600, 8687])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 18ms/step


array([[ 2.5551725e-02,  3.1417418e-02, -3.6782194e-02,  1.4736876e-03,
        -2.9133404e-02,  1.2335978e-02, -4.5650791e-02, -4.9263455e-02,
         3.4545470e-02,  1.1306070e-02],
       [ 2.5551725e-02,  3.1417418e-02, -3.6782194e-02,  1.4736876e-03,
        -2.9133404e-02,  1.2335978e-02, -4.5650791e-02, -4.9263455e-02,
         3.4545470e-02,  1.1306070e-02],
       [ 2.5551725e-02,  3.1417418e-02, -3.6782194e-02,  1.4736876e-03,
        -2.9133404e-02,  1.2335978e-02, -4.5650791e-02, -4.9263455e-02,
         3.4545470e-02,  1.1306070e-02],
       [ 2.5551725e-02,  3.1417418e-02, -3.6782194e-02,  1.4736876e-03,
        -2.9133404e-02,  1.2335978e-02, -4.5650791e-02, -4.9263455e-02,
         3.4545470e-02,  1.1306070e-02],
       [ 2.4896488e-03, -4.9707450e-02,  1.5184831e-02,  2.0734679e-02,
        -4.9455650e-03,  4.3300737e-02, -1.9598497e-02,  2.0258058e-02,
         9.1357604e-03, -2.4207080e-02],
       [-2.6992226e-02, -3.3454705e-02, -2.2393977e-02,  3.8473498e-02,
   