### Numpy's most useful feature is n dimensional array object (a.k.a ndarray)

In [2]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a[0]

1

In [5]:
a[1]

2

### It is same like python list but what's special about it?

3 main benfits of numpy array over a python list,
1. Less Memory
2. Fast
3. Convinient


Comparing the python lists and numpy array.

In [7]:
import numpy as np
import time
import sys

### size took by pythonlist and numpy array

In [14]:
l = range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [15]:
array = np.arange(1000)
print(array.size*array.itemsize)

4000


### Time took for adding the lists and numpy array

In [28]:
size = 10000000
l1 = range(size)
l2 = range(size)
a1 = np.arange(size)
a2 = np.arange(size)

In [29]:
#pythonlist
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took : ", (time.time()-start)*1000) #to convert seconds to milli seconds *1000

python list took :  897.0329761505127


In [30]:
#numpy array
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000)  #to convert seconds to milli seconds *1000

numpy took:  151.5982151031494


In [31]:
num_list = [3,2,4,5,7,8]
print(num_list * 2) #it doubles the elements in the list 

[3, 2, 4, 5, 7, 8, 3, 2, 4, 5, 7, 8]


In [32]:
[val*2 for val in num_list]

[6, 4, 8, 10, 14, 16]

In [33]:
import numpy as np

n1 = np.array(num_list)
print(n1)

[3 2 4 5 7 8]


In [34]:
print(n1*3)

[ 9  6 12 15 21 24]


In [35]:
print(n1.ndim)

1


In [39]:
#array() - to create an array using numpy
n2 = np.array([[5,7,8,3,2] , [15,71,25,6,31] , [2,6,9,4,3]])
print(n2)

[[ 5  7  8  3  2]
 [15 71 25  6 31]
 [ 2  6  9  4  3]]


In [40]:
print(n2.shape)
print(n2.ndim)
print(n2.size)

(3, 5)
2
15


In [41]:
print(n2)

[[ 5  7  8  3  2]
 [15 71 25  6 31]
 [ 2  6  9  4  3]]


In [42]:
#indexing in numpy
print(n2[1,2])
print(n2[2,3])
print(n2[2,1])

25
4
6


In [51]:
#slicing
#array[initial_row_index : initial_row_index + number_of_rows, initial_column_index : initial_column_index + number_of_columns]
print(n2[1:3,2:4])

[[25  6]
 [ 9  4]]


In [72]:
#arrange => to define an array in a given range
n3 = np.arange(1,37)
print(n3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [73]:
#reshape an array => reshape()
#36 => (1,36), (36,1), (2,18), (18,2), (3,12), (12,3), (4,9), (9,4) , (6,6)

n4 = n3.reshape(6,6)
print(n4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [74]:
print(n4[3:,3:])

[[22 23 24]
 [28 29 30]
 [34 35 36]]


In [75]:
#to separate 1st column
print(n4[: , 0:1])

[[ 1]
 [ 7]
 [13]
 [19]
 [25]
 [31]]


In [76]:
print(n4[4:5 , :])

[[25 26 27 28 29 30]]


### funcions in numpy

In [77]:
print(np.mean(n4))
print(np.sum(n4))
print(np.prod(n4))
print(np.min(n4))
print(np.std(n4))
print(np.argmax(n4))
print(np.argmin(n4))

18.5
666
0
1
10.388294694831615
35
0


In [78]:
print(n4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [79]:
#axis in numpy functions, axis=0 => calculate for each column

print(np.mean(n4 , axis = 0))
print(np.sum(n4, axis = 0))
print(np.prod(n4, axis = 0))
print(np.min(n4, axis = 0))
print(np.std(n4, axis = 0))
print(np.argmax(n4, axis = 0))
print(np.argmin(n4, axis = 0))

[16. 17. 18. 19. 20. 21.]
[ 96 102 108 114 120 126]
[ 1339975  3727360  7577955 13404160 21827575 33592320]
[1 2 3 4 5 6]
[10.24695077 10.24695077 10.24695077 10.24695077 10.24695077 10.24695077]
[5 5 5 5 5 5]
[0 0 0 0 0 0]


In [80]:
#axis in numpy functions, axis=1 => calculate for each row

print(np.mean(n4 , axis = 1))
print(np.sum(n4, axis = 1))
print(np.prod(n4, axis = 1))
print(np.min(n4, axis = 1))
print(np.std(n4, axis = 1))
print(np.argmax(n4, axis = 1))
print(np.argmin(n4, axis = 1))

[ 3.5  9.5 15.5 21.5 27.5 33.5]
[ 21  57  93 129 165 201]
[       720     665280   13366080   96909120  427518000 1402410240]
[ 1  7 13 19 25 31]
[1.70782513 1.70782513 1.70782513 1.70782513 1.70782513 1.70782513]
[5 5 5 5 5 5]
[0 0 0 0 0 0]


In [81]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [83]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
np.random.randint(0,20)

16

In [88]:
np.random.randint(0,20, size=(3,2))

array([[ 3,  0],
       [ 5, 14],
       [17,  9]])

In [89]:
print(n2)

[[ 5  7  8  3  2]
 [15 71 25  6 31]
 [ 2  6  9  4  3]]


In [90]:
np.where(n2 == 25)

(array([1], dtype=int64), array([2], dtype=int64))

In [95]:
#dot product using numpy

a = np.array([[4,5,7,2] , [7,4,9,3] , [9,1,1,2]])
print(a)

[[4 5 7 2]
 [7 4 9 3]
 [9 1 1 2]]


In [96]:
b = np.array([[2,1,2,2] , [1,3,3,1]])
print(b)

[[2 1 2 2]
 [1 3 3 1]]


In [99]:
print(np.dot(a,b.T))

[[31 42]
 [42 49]
 [25 17]]


In [101]:
#3x + 2y + z = 7
#2x + 3y + 5z = 14
#3x + 4y + 3z = 21

A=np.array([[3,2,1],[2,3,5],[3,4,3]])
print(A)

[[3 2 1]
 [2 3 5]
 [3 4 3]]


In [102]:
B = np.array([[7],[14],[21]])
print(B)

[[ 7]
 [14]
 [21]]


In [103]:
#A.X = B
#X = inv(A).B

Ainv = np.linalg.inv(A)
print(Ainv)

[[ 0.6875  0.125  -0.4375]
 [-0.5625 -0.375   0.8125]
 [ 0.0625  0.375  -0.3125]]


In [104]:
X = np.dot(Ainv,B)
print(X)

[[-2.625]
 [ 7.875]
 [-0.875]]


In [105]:
np.dot(A,X)

array([[ 7.],
       [14.],
       [21.]])

* Broadcasting
  * It's a mechanism that allows array of different shapes to combined together for         arrithmetic operations.
  * It helps to perform operations even if the arrays do not have same shapes, by implicitly extending the smaller array to match the shape of larger one.

In [106]:
n1 = np.array([[4,1,3],[2,7,6]])
print(n1)

[[4 1 3]
 [2 7 6]]


In [107]:
k = 5

In [108]:
print(n1 * 5)

[[20  5 15]
 [10 35 30]]


In [109]:
#Broadcasting for columns 

n2 = np.array([[1],[2]])
print(n2)

[[1]
 [2]]


In [110]:
print(n1 * n2)

[[ 4  1  3]
 [ 4 14 12]]


In [113]:
#Broadcasting for rows

n3 = np.array([[3,2,1]])
print(n3)

[[3 2 1]]


In [114]:
print(n1)

[[4 1 3]
 [2 7 6]]


In [115]:
print(n1 * n3)

[[12  2  3]
 [ 6 14  6]]


In [116]:
#two array with same shape

n4 = np.array([[2,3,1],[1,2,3]])
print(n4)

[[2 3 1]
 [1 2 3]]


In [117]:
print(n1)

[[4 1 3]
 [2 7 6]]


In [118]:
n5 = np.array([[1,2,3,5]])
print(n1 * n5)

ValueError: operands could not be broadcast together with shapes (2,3) (1,4) 

In [120]:
#joining or stacking 

#vertical stacking

n1 = np.array([[2,3,4],[1,2,3]])
print(n1)
print("*****")
n2 = np.array([[3,4,5]])
print(n2)

[[2 3 4]
 [1 2 3]]
*****
[[3 4 5]]


In [121]:
n3 = np.vstack((n1,n2))
print(n3)


[[2 3 4]
 [1 2 3]
 [3 4 5]]


In [122]:
#Horizontal stack

n1 = np.array([[2,3,4],[1,2,3]])
print(n1)
print("*****")
n4 = np.array([[11,12],[13,15]])
print(n4)

[[2 3 4]
 [1 2 3]]
*****
[[11 12]
 [13 15]]


In [123]:
n5 = np.hstack((n1,n4))
print(n5)

[[ 2  3  4 11 12]
 [ 1  2  3 13 15]]


In [124]:
n1=np.array([[2,3,4],[1,2,3]])
print(n1)
print("*****")
n4=np.array([[11,12],[13,15]])
print(n4)

[[2 3 4]
 [1 2 3]]
*****
[[11 12]
 [13 15]]


In [128]:
#Concatenate horizontally , axis=1
np.concatenate((n1,n4),axis=1)

array([[ 2,  3,  4, 11, 12],
       [ 1,  2,  3, 13, 15]])

In [129]:
#Concatenate Vertically , axis=0
np.concatenate((n1,n2),axis=0)

array([[2, 3, 4],
       [1, 2, 3],
       [3, 4, 5]])